dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install pytest
script:
  - pytest
  
#these commands will help the rmeote server that we want to run
#our automated testing on get configured in the right way to do so